# server
server:
  port: 8081
  servlet:
    context-path: /bk


# mybatis
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.jerrmy.bookkeeping.entity


# mysql
spring:
  datasource:
    url: jdbc:mysql://192.168.22.128:3306/bookkeeping?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

# limit
limit:
  min-money: 11
  max-money: 9999
  description: minMoney ${limit.min-money},maxMoney ${limit.max-money}
